tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "sass/sass"
brew "anyenv"
brew "openssl@3"
brew "readline"
brew "sqlite"
brew "php@8.0", restart_service: true, link: true
brew "pyenv"
brew "xz"
brew "yarn"
brew "zlib"
